### ISSUE TITLE
Your gitignore might fuck your project up

### ISSUE THREAD

**Issue by mequidis** [roeyba/chess-ui#2]
you have captcha files in bin/Debug/captcha and they might get deleted because gitignore deletes everything in bin/Debug
also run ```git rm --cached -r .; git add .; git commit -m "apply gitignore"``` to apply gitignore :)

**Comment by roeyba** [comment]
Wow i thought i had to manually remove the tracking for each file i committed

**Comment by roeyba** [comment]
you were right
i fixed it but i still left some files tracked inside a debug folder

**Comment by mequidis** [comment]
I am so proud I am going to shed a tear :sob: :sob: :sob:
